<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>{{ $title }}</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 9pt;
            color: #333;
            padding: 20px;
        }

        .report-header {
            text-align: center;
            margin-bottom: 8px;
        }

        .report-title {
            font-size: 16pt;
            font-weight: bold;
            color: #D32F2F;
            margin-bottom: 4px;
            text-transform: uppercase;
            letter-spacing: 1px;
        }

        .report-meta {
            font-size: 9pt;
            color: #666;
            font-style: italic;
        }

        .chart-container {
            text-align: center;
            margin: 15px 0;
            page-break-inside: avoid;
        }

        .chart-container img {
            max-width: 100%;
            height: auto;
            border: 1px solid #ddd;
            border-radius: 4px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
            page-break-inside: auto;
        }

        thead {
            display: table-header-group;
        }

        tr {
            page-break-inside: avoid;
            page-break-after: auto;
        }

        th {
            background-color: #D32F2F;
            color: #fff;
            font-weight: bold;
            text-align: center;
            padding: 8px 6px;
            font-size: 9pt;
            border: 1px solid #B71C1C;
        }

        td {
            padding: 5px 6px;
            border: 1px solid #ccc;
            font-size: 8.5pt;
            vertical-align: middle;
        }

        td.text-col {
            text-align: left;
        }

        td.number-col {
            text-align: right;
        }

        td.currency-col {
            text-align: right;
        }

        tbody tr:nth-child(even) {
            background-color: #f9f9f9;
        }

        tbody tr:hover {
            background-color: #f0f0f0;
        }

        .footer {
            margin-top: 20px;
            text-align: center;
            font-size: 8pt;
            color: #999;
            border-top: 1px solid #ddd;
            padding-top: 8px;
        }

        .no-data {
            text-align: center;
            padding: 30px;
            color: #999;
            font-style: italic;
        }
    </style>
</head>
<body>
    <div class="report-header">
        <div class="report-title">{{ $title }}</div>
        <div class="report-meta">{{ $generatedAt }}</div>
    </div>

    @if($chartImage)
    <div class="chart-container">
        <img src="{{ $chartImage }}" alt="Chart">
    </div>
    @endif

    @if(count($rows) > 0)
    <table>
        <thead>
            <tr>
                @foreach($headers as $header)
                    <th>{{ $header }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @foreach($rows as $rowIndex => $row)
            <tr>
                @foreach($row as $colIndex => $cell)
                    @php
                        $colType = $columnTypes[$colIndex] ?? 'text';
                        $class = $colType === 'number' ? 'number-col' : ($colType === 'currency' ? 'currency-col' : 'text-col');

                        // Format currency
                        if ($colType === 'currency' && is_numeric($cell)) {
                            $cell = number_format($cell, 0, ',', '.');
                        }
                    @endphp
                    <td class="{{ $class }}">{{ $cell }}</td>
                @endforeach
            </tr>
            @endforeach
        </tbody>
    </table>
    @else
    <div class="no-data">Tidak ada data untuk ditampilkan</div>
    @endif

    <div class="footer">
        Generated by darkotech AI &bull; {{ date('Y') }}
    </div>
</body>
</html>
